package com.uop.efac.cc.award.Enum;

public enum Award {
    AWARD1("THE C.A. HEWAVITHARANA MEMORIAL PRIZE IN ENGINEERING"),
    AWARD2("THE CEYLON DEVELOPMENT ENGINEERING PRIZE FOR CIVIL ENGINEERING"),
    AWARD3("CEYLON ELECTRICITY BOARD GOLD MEDAL AND PRICE FOR ELECTRICAL AND ELECTRONIC ENGINEERING"),
    AWARD4("THE CHANNA LALITH MADDUMAGE MEMORIAL PRIZE FOR MECHANICAL ENGINEERING"),
    AWARD5("THE COLOMBO DOCKYARD PRIZE FOR PRODUCTION ENGINEERING"),
    AWARD6("THE BIECO-LINK CARBONS PRIZE FOR CHEMICAL ENGINEERING"),
    AWARD7("REGULATIONS GOVERNING THE AWARD OF THYAPRAKASAPILLAI PRIZE FOR INDUSTRIAL ENGINEERING"),
    AWARD8("REGULATIONS GOVERNING THE AWARD OF JB DISSANAYAKE PRIZE"),
    AWARD9("REGULATIONS GOVERNING THE AWARD OF EF BARTHOLOMEUSZ PRIZE FOR ENGINEERING MATHEMATICS"),
    AWARD10("REGULATIONS GOVERNING THE AWARD OF EOE PEREIRA PRIZE FOR STRUCTURES(I)"),
    AWARD11("REGULATIONS GOVERNING THE AWARD OF EOE PEREIRA PRIZE FOR STRUCTURES(II)"),
    AWARD12("REGULATIONS GOVERNING THE AWARD OF HB de SILVA PRIZE FOR SURVEYING"),
    AWARD13("REGULATIONS GOVERNING THE AWARD OF A THURAIRAJAH PRIZE FOR GEOTECHNICSG"),
    AWARD14("REGULATIONS GOVERNING THE AWARD OF AMAMARATHUNGA PRIZE FOR STRENGTH OF MATERIALS"),
    AWARD15("REGULATIONS GOVERNING THE AWARD OF RHPAUL PRIZE FOR ELECTRICAL POWER AND MACHINES"),
    AWARD16("REGULATIONS GOVERNING THE AWARD OF WMG FERNANDO PRIZE FOR ELECTRONIC COMMUNICATIONS"),
    AWARD17("REGULATIONS GOVERNING THE AWARD OF JVC CHINNAPPA PRIZE FOR ENERGY STUDIES"),
    AWARD18("REGULATIONS GOVERNING THE AWARD OF LRL PERERA PRIZE FOR THERMODYNAMICS"),
    AWARD19("REGULATIONS GOVERNING THE AWARD OF S MAHALINGAM PRIZE FOR MECHANICS OF MACHINES"),
    AWARD20("EGULATIONS GOVERNING THE AWARD OF W.P. JAYASEKARA PRIZE FOR THE BEST STUDENT PROTECT IN ELECTRICAL & ELECTRONIC ENGINEERING"),
    AWARD21("REGULATIONS GOVERNING THE AWARD OF P.M RANAWEERA PRIZE FOR COMPUTER AIDED STRUCTURAL DESIGN"),
    AWARD22("REGULATIONS GOVERNING THE AWARD OF MP RANAWEERA PRIZE FOR FINITE ELEMENT METHODS IN SOLID MECHANICS"),
    AWARD23("PROFESSOR T.D.M.A SAMUEL PRIZE FOR AND ENTHUSIASM AND EXCELLENCE IN ENGINEERING MATHEMATICS"),
    AWARD24("PROFESSOR J.A GUNAWARDENA PRIZE FOR THE BEST PERFORMANCE IN CONTROL ENGINEERING"),
    AWARD25("PROFESSOR J.A GUNAWARDENA PRIZE FOR THE BEST PERFORMANCE IN ELECTRONICAL ENGINEERING");

    private String award;

    Award(String award){ this.award = award; }

    public String getAward() {
        return award;
    }
}
